export { default as NowPlaying } from './NowPlaying'
export { default as Popular } from './Popular'
export { default as TopRated } from './TopRated'
export { default as MovieDetail } from './MovieDetail'
export { default as Home } from './Home'